### ISSUE TITLE
Possibly internationalization related problem

### ISSUE THREAD

**Issue by ErdemYabaci** [Arquisoft/wiq_en1b#58]
I was sometimes getting this error while the languageCode was "es". It might be a fluke but issue solved itself when I removed the lines where languageCode = "es" was used.

Error:
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.wikidata.wdtk.datamodel.interfaces.MonolingualTextValue.getText()" because "mtv" is null
        at main.java.questionGenerator.generator.AbstractGenerator.getName(AbstractGenerator.java:79)
        at main.java.questionGenerator.generator.RightAnswerIsEntity.getRightAnswer(RightAnswerIsEntity.java:30)
        at main.java.questionGenerator.generator.RightAnswerIsEntity.getAnswer(RightAnswerIsEntity.java:58)
        at main.java.questionGenerator.generator.specificGenerators.CapitalGenerator.getWrongAnswers(CapitalGenerator.java:32)
        at main.java.questionGenerator.generator.AbstractGenerator.generate(AbstractGenerator.java:69)
        at main.java.questionGenerator.QuestionGenerator.generateQuestion(QuestionGenerator.java:31)
        at main.java.Main.run(Main.java:37)
        at main.java.Main.main(Main.java:17)
```

**Comment by UO289845** [comment]
Ok so as it turns out is way more complex than I thought. The entity that gives up the problem is Q17 (Japan), but not because Tokyo does not have a value in Spanish, but because is not selecting Tokyo as the capital. Is selecting Shigaraki Palace (Q262438), which technically speaking it seems to have been correct (around the year 744). This is because is picking up the first result in the capital, which is not necesarily the correct one.

Now I'll try to came up with an algorithm to ensure it picks the correct capital.

**Comment by UO289845** [comment]
Is finally solved and in the Question_Generation_General branch
